language: php
php:
  - 5.5
  - 7.0
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
cache:
  directories:
    - vendor/
    - $HOME/.composer/cache
